version: '3'

services:

  app:
    build:
      context: .
      dockerfile: .docker/PHP/Dockerfile
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    links:
      - bancodedados

  bancodedados:
    build: 
      context: .
      dockerfile: .docker/DB/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: my_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: 123456

  phpqa:
    image: jakzal/phpqa:php7.1-alpine

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9000:80"
    links:
      - "bancodedados:db"